import os
import json
from pathlib import Path
from dotenv import load_dotenv
from pinecone import Pinecone, ServerlessSpec
from langchain_pinecone import PineconeVectorStore
from langchain_ollama import OllamaEmbeddings
from langchain_core.documents import Document
from uuid import uuid4


def find_env_file(start_path: Path | None = None) -> Path | None:
    """Search upward from start_path for a .env file."""
    if start_path is None:
        start_path = Path(__file__).resolve().parent

    current = start_path
    while current != current.parent:
        candidate = current / ".env"
        if candidate.is_file():
            return candidate
        current = current.parent
    return None

project_root = Path(__file__).resolve().parent
env_path = find_env_file(project_root)

if env_path:
    load_dotenv(dotenv_path=env_path)
else:
    load_dotenv()

os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")
os.environ["LANGCHAIN_API_KEY"] = os.getenv("LANGCHAIN_API_KEY")
os.environ["LANGCHAIN_PROJECT"] = os.getenv("LANGCHAIN_PROJECT")
os.environ["LANGCHAIN_TRACING_V2"] = os.getenv("LANGCHAIN_TRACING_V2")
os.environ["PINECONE_API_KEY"] = os.getenv("PINECONE_API_KEY")
os.environ["PINECONE_ENVIRONMENT"] = os.getenv("PINECONE_ENVIRONMENT")

pinecone_key = os.environ["PINECONE_API_KEY"]
if pinecone_key:
    try:
        pc = Pinecone(api_key=pinecone_key)
        indexes = pc.list_indexes()  # call the method
        # In the new SDK, .names is an attribute (list-like), not a method
        names = list(indexes.names())
        # print(f"✅ Pinecone is working. Found {len(names)} index(es): {names}")
        #print(pc.has_index(names[0]))
        #print(names)
        #print(list(indexes.names())#)

        new_index = "rag-learning-september2026"
        if new_index not in names:
            pc.create_index(
                name=new_index,
                dimension=768,  # ollama embedding
                metric="cosine",
                spec=ServerlessSpec(
                    cloud="aws",
                    region="us-east-1"  # or another supported region
                ),
                deletion_protection="disabled"
            )
            print(f"✅ Index '{new_index}' created.")
        else:
            print(f"ℹ️  Index '{new_index}' already exists.")

       # print(new_index)

        ollama_embedder = OllamaEmbeddings(
            model="nomic-embed-text:latest"
        )

        vector_index = pc.Index(new_index)
        vector_store = PineconeVectorStore(index=vector_index, embedding=ollama_embedder)

        docs = [
            Document(
                page_content="Social robot companions may collect speech, behaviour, and personal interaction data.",
                metadata={"source": "social", "doc_id": "doc_1"}
            ),
            Document(
                page_content="News reports highlight growing concerns about privacy and consent in human-robot interaction.",
                metadata={"source": "news", "doc_id": "doc_2"}
            ),
            Document(
                page_content="A blog post argues that emotional attachment to robots could reshape social norms.",
                metadata={"source": "blog", "doc_id": "doc_3"}
            ),
            Document(
                page_content="Researchers warn that companion robots might record sensitive conversations in private spaces.",
                metadata={"source": "social", "doc_id": "doc_4"}
            ),
            Document(
                page_content="An article discusses how robot data could be shared with third-party services.",
                metadata={"source": "news", "doc_id": "doc_5"}
            ),
            Document(
                page_content="A study suggests that users often anthropomorphize social robots and trust them more than expected.",
                metadata={"source": "blog", "doc_id": "doc_6"}
            ),
            Document(
                page_content="News coverage describes cases where robot assistants influenced daily routines and decisions.",
                metadata={"source": "social", "doc_id": "doc_7"}
            ),
            Document(
                page_content="A blog entry compares robot companions to pets and examines the ethical implications.",
                metadata={"source": "news", "doc_id": "doc_8"}
            ),
            Document(
                page_content="Social scientists investigate how children form bonds with educational robots.",
                metadata={"source": "blog", "doc_id": "doc_9"}
            ),
            Document(
                page_content="A news story raises questions about who owns the data generated by home robots.",
                metadata={"source": "social", "doc_id": "doc_10"}
            ),
            Document(
                page_content="A blog post explores whether robot companionship could reduce loneliness in older adults.",
                metadata={"source": "news", "doc_id": "doc_11"}
            ),
            Document(
                page_content="Researchers propose guidelines for transparent data handling in social robot systems.",
                metadata={"source": "blog", "doc_id": "doc_12"}
            ),
            Document(
                page_content="An article examines legal frameworks for robot data protection in Europe.",
                metadata={"source": "social", "doc_id": "doc_13"}
            ),
            Document(
                page_content="A news report covers a company that uses robot-collected data to personalise advertising.",
                metadata={"source": "news", "doc_id": "doc_14"}
            ),
            Document(
                page_content="A blog entry debates whether robots should be allowed to make recommendations about health.",
                metadata={"source": "blog", "doc_id": "doc_15"}
            ),
            Document(
                page_content="Social studies show that some users disclose personal problems to robots they perceive as non-judgmental.",
                metadata={"source": "social", "doc_id": "doc_16"}
            ),
            Document(
                page_content="A news feature describes robots that adapt their behaviour based on long-term user patterns.",
                metadata={"source": "news", "doc_id": "doc_17"}
            ),
            Document(
                page_content="A blog post questions whether emotional dependency on robots is desirable or risky.",
                metadata={"source": "blog", "doc_id": "doc_18"}
            ),
            Document(
                page_content="Researchers test whether explicit privacy settings improve user trust in robot companions.",
                metadata={"source": "social", "doc_id": "doc_19"}
            ),
            Document(
                page_content="An article summarises public attitudes toward robots that continuously listen and observe.",
                metadata={"source": "news", "doc_id": "doc_20"}
            ),
        ]

        # ---- Load or create UUID registry ----
        REGISTRY_PATH = Path("doc_uuid_registry.json")

        if REGISTRY_PATH.exists():
            registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
            print("ℹ️  Loaded existing UUID registry.")
        else:
            registry = {}
            print("ℹ️  No registry found; creating new UUIDs for all docs.")

        # Assign UUIDs: reuse existing, create new only for unknown doc_ids
        for doc in docs:
            doc_id = doc.metadata["doc_id"]
            if doc_id in registry:
                # Reuse existing UUID
                doc.metadata["doc_uuid"] = registry[doc_id]
            else:
                # Generate new UUID and store it
                new_uuid = str(uuid4())
                doc.metadata["doc_uuid"] = new_uuid
                registry[doc_id] = new_uuid

        # Save updated registry
        REGISTRY_PATH.write_text(json.dumps(registry, indent=2), encoding="utf-8")
        print("✅ Registry saved/updated:", REGISTRY_PATH)

        # Use stable vector IDs based on doc_uuid
        ids = [doc.metadata["doc_uuid"] for doc in docs]

        vector_store.add_documents(documents=docs, ids=ids)

        # --- Similarity Search ---
        results_simple = vector_store.similarity_search(
            "What are ethical aspects of social robots?",
            k=1
        )
        print(results_simple)

    except Exception as e:
        print(f"❌ Pinecone run failed: {e}")
else:
    print("\nℹ️  No PINECONE_API_KEY in environment; skipping Pinecone run.")


