import os
from pathlib import Path

from dotenv import load_dotenv
from langchain_ollama import OllamaEmbeddings
from langchain_core.documents import Document
from langchain_chroma import Chroma


def find_env_file(start_path: Path | None = None) -> Path | None:
    """Search upward from start_path for a .env file."""
    if start_path is None:
        start_path = Path(__file__).resolve().parent

    current = start_path
    while current != current.parent:
        candidate = current / ".env"
        if candidate.is_file():
            return candidate
        current = current.parent
    return None

project_root = Path(__file__).resolve().parent
env_path = find_env_file(project_root)

if env_path:
    load_dotenv(dotenv_path=env_path)
else:
    load_dotenv()

docs = [
    Document(
        page_content="Social robot companions may collect speech, behaviour, and personal interaction data.",
        metadata={"source": "social", "doc_id": "doc_1"}
    ),
    Document(
        page_content="News reports highlight growing concerns about privacy and consent in human-robot interaction.",
        metadata={"source": "news", "doc_id": "doc_2"}
    ),
    Document(
        page_content="A blog post argues that emotional attachment to robots could reshape social norms.",
        metadata={"source": "blog", "doc_id": "doc_3"}
    ),
    Document(
        page_content="Researchers warn that companion robots might record sensitive conversations in private spaces.",
        metadata={"source": "social", "doc_id": "doc_4"}
    ),
    Document(
        page_content="An article discusses how robot data could be shared with third-party services.",
        metadata={"source": "news", "doc_id": "doc_5"}
    ),
    Document(
        page_content="A study suggests that users often anthropomorphize social robots and trust them more than expected.",
        metadata={"source": "blog", "doc_id": "doc_6"}
    ),
    Document(
        page_content="News coverage describes cases where robot assistants influenced daily routines and decisions.",
        metadata={"source": "social", "doc_id": "doc_7"}
    ),
    Document(
        page_content="A blog entry compares robot companions to pets and examines the ethical implications.",
        metadata={"source": "news", "doc_id": "doc_8"}
    ),
    Document(
        page_content="Social scientists investigate how children form bonds with educational robots.",
        metadata={"source": "blog", "doc_id": "doc_9"}
    ),
    Document(
        page_content="A news story raises questions about who owns the data generated by home robots.",
        metadata={"source": "social", "doc_id": "doc_10"}
    ),
    Document(
        page_content="A blog post explores whether robot companionship could reduce loneliness in older adults.",
        metadata={"source": "news", "doc_id": "doc_11"}
    ),
    Document(
        page_content="Researchers propose guidelines for transparent data handling in social robot systems.",
        metadata={"source": "blog", "doc_id": "doc_12"}
    ),
    Document(
        page_content="An article examines legal frameworks for robot data protection in Europe.",
        metadata={"source": "social", "doc_id": "doc_13"}
    ),
    Document(
        page_content="A news report covers a company that uses robot-collected data to personalise advertising.",
        metadata={"source": "news", "doc_id": "doc_14"}
    ),
    Document(
        page_content="A blog entry debates whether robots should be allowed to make recommendations about health.",
        metadata={"source": "blog", "doc_id": "doc_15"}
    ),
    Document(
        page_content="Social studies show that some users disclose personal problems to robots they perceive as non-judgmental.",
        metadata={"source": "social", "doc_id": "doc_16"}
    ),
    Document(
        page_content="A news feature describes robots that adapt their behaviour based on long-term user patterns.",
        metadata={"source": "news", "doc_id": "doc_17"}
    ),
    Document(
        page_content="A blog post questions whether emotional dependency on robots is desirable or risky.",
        metadata={"source": "blog", "doc_id": "doc_18"}
    ),
    Document(
        page_content="Researchers test whether explicit privacy settings improve user trust in robot companions.",
        metadata={"source": "social", "doc_id": "doc_19"}
    ),
    Document(
        page_content="An article summarises public attitudes toward robots that continuously listen and observe.",
        metadata={"source": "news", "doc_id": "doc_20"}
    ),
]

ollama_embedder = OllamaEmbeddings(
    model="nomic-embed-text:latest"
)

doc_texts = [doc.page_content for doc in docs]
doc_metadata = [doc.metadata for doc in docs]
doc_vectors = ollama_embedder.embed_documents(doc_texts)

#print(len(doc_vectors)) #20
#print(len(doc_vectors[0])) #768

vector_store = Chroma.from_texts(
    texts=doc_texts,
    embedding=ollama_embedder,
    metadatas=doc_metadata,
    persist_directory="./chroma_test_db",
)

vector_list = vector_store.add_documents(documents=docs)
#print(vector_list)

#---Similarity Search---
results_simple= vector_store.similarity_search("What are ethical aspects of social robots?", k=1)
#print(results_simple)

#---Similarity Search with metadata filter---
results_by_source = vector_store.similarity_search(
    "What are robots?",
    k=1,
    filter={"source": "news"}
)
print(results_by_source)